#!/usr/bin/env sh
set -eu

[ "$#" -gt 1 ] && { echo "Usage: $0 <kernel_release>" >&2; exit 1; }
KERNEL_RELEASE="${1:-$(uname -r)}"

./download_and_patch
cd NVIDIA-Linux-x86_64-470.256.02/kernel
SYSSRC=/lib/modules/${KERNEL_RELEASE}/build/ make "-j$(nproc)"
