# Test the build against the EL9.8's kernel
# https://github.com/orgs/AlmaLinux/packages/container/package/9-base
FROM ghcr.io/almalinux/9-base:9.8

RUN dnf -y update --allowerasing \
    && dnf -y install --setopt=install_weak_deps=False \
        wget \
        gcc make patch \
        kernel-devel

# We take el8 driver first via dnf before patching
# dnf-plugin-nvidia; however, comes from el9
RUN echo "$0: setting up repo file..." \
   && date \
   && wget -O /etc/yum.repos.d/cuda-rhel8.repo http://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo \
   && wget -O /etc/yum.repos.d/cuda-rhel9.repo http://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo \
   && ls -al /etc/yum.repos.d/cuda-rhel8.repo \
   && ls -al /etc/yum.repos.d/cuda-rhel9.repo \
   && dnf list nvidia-driver-cuda \
   && dnf -y --enablerepo=cuda-rhel9-x86_64 install dnf-plugin-nvidia \
   && dnf -y --enablerepo=cuda-rhel8-x86_64 module list nvidia-driver \
   && dnf -y --enablerepo=cuda-rhel8-x86_64 module enable nvidia-driver:470-dkms \
   && dnf -y install nvidia-driver nvidia-driver-cuda

RUN dnf clean all \
    && rm -rf /var/cache/dnf

WORKDIR /app

COPY . .

# Create entrypoint script to set up kernel build paths
RUN printf '%s\n' \
    '#!/bin/sh' \
    'KERNEL_BASE_DIR=$(echo /usr/src/kernels/*)' \
    'SYSSRC=$KERNEL_BASE_DIR exec "$@"' \
  > /entrypoint.sh && chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

CMD ["echo ./el9-buildtest TODO"]
