#!/usr/bin/env sh
set -eu

if [ "$(id -u)" -eq 0 ]; then
    ASROOT=
elif command -v doas >/dev/null 2>&1; then
    ASROOT=doas
elif command -v sudo >/dev/null 2>&1; then
    ASROOT=sudo
else
    echo "Please install doas or sudo, or this script as root" >&2
    exit 1
fi

./extract_and_patch
cd NVIDIA-Linux-x86_64-470.256.02
$ASROOT ./nvidia-installer "$@"
