name: Build test NVIDIA driver patches

on:
  push:
    branches: [ master, el9 ]
  pull_request:
  workflow_dispatch:

jobs:
  build-validation:
    runs-on: ubuntu-latest
    strategy:
      # Don't fail all elements of the matrix if one fails
      fail-fast: false
      matrix:
        #kernel: [legacy, stable, mainline, ubuntu-devel, el9]
        kernel: [ el9 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build against the ${{ matrix.kernel }} kernel
        run: make test-${{ matrix.kernel }}

      - name: Build against the ${{ matrix.kernel }} kernel with staging patches
        run: make test-${{ matrix.kernel }}-staging
